# --- Basic Site Info ---
title: "Merveille Dona CODJO"
lang: fr
logo: img/pic.jpg

# --- Theme Configuration ---
theme: jekyll-theme-minimal
show_downloads: false   # only true if you want a download button


# --- Author Information ---
author:
  name: "Merveille Dona CODJO"
  email: "merveilledonacodjo@gmail.com"
  linkedin: "https://www.linkedin.com/in/merveillecodjo/"
  github: "https://github.com/merveille-dona"

# --- Custom Options (Jekyll-Minimal supports these) ---
social_links:
  - name: LinkedIn
    url:  "https://www.linkedin.com/in/merveillecodjo/"
  - name: GitHub
    url: "https://github.com/merveille-dona"
  - name: Email
    url: "merveilledonacodjo@gmail.com"

# --- URL & Metadata ---
url: "https://merveille-dona.github.io"
